namespace PromptStudio.Core.Domain;

/// <summary>
/// Represents the lifecycle states of AI-generated workflow suggestions within the review and implementation process.
/// 
/// <para><strong>Business Context:</strong></para>
/// Suggestion status enables systematic tracking of improvement recommendations from initial generation
/// through review, decision-making, and implementation phases. This workflow ensures accountability,
/// maintains audit trails, and supports collaborative decision-making processes for workflow optimization.
/// 
/// <para><strong>Technical Context:</strong></para>
/// Status transitions follow a defined state machine that supports workflow approval processes,
/// implementation tracking, and outcome measurement. The status system integrates with notification
/// systems, reporting dashboards, and automated workflow optimization engines.
/// 
/// <para><strong>Value Proposition:</strong></para>
/// - Structured suggestion management and accountability
/// - Clear visibility into optimization pipeline
/// - Support for collaborative review processes
/// - Measurable improvement tracking and outcomes
/// </summary>
/// <remarks>
/// <para><strong>State Transitions:</strong></para>
/// Typical flow: Pending → UnderReview → Accepted/Rejected/Deferred → Implemented
/// 
/// <para><strong>Usage Guidelines:</strong></para>
/// - Status changes should include timestamps and user attribution
/// - Rejected suggestions should include reasoning for future analysis
/// - Implemented suggestions should link to actual changes made
/// - Deferred suggestions should include timeline expectations
/// 
/// <para><strong>Integration Points:</strong></para>
/// - Workflow management systems for implementation tracking
/// - Notification services for status change alerts
/// - Analytics platforms for suggestion effectiveness measurement
/// </remarks>
/// <example>
/// A Performance suggestion moves from Pending → UnderReview (by team lead) → 
/// Accepted → Implemented (with metrics showing 25% speed improvement).
/// </example>
public enum SuggestionStatus
{
    /// <summary>
    /// Initial status when a suggestion is first generated by AI analysis.
    /// Indicates the suggestion is awaiting initial review and triage.
    /// </summary>
    Pending = 0,
    
    /// <summary>
    /// The suggestion has been accepted for implementation.
    /// Indicates stakeholder approval and commitment to apply the recommended changes.
    /// </summary>
    Accepted = 1,
    
    /// <summary>
    /// The suggestion has been reviewed and rejected.
    /// Indicates the recommendation was evaluated but deemed inappropriate or unnecessary.
    /// </summary>
    Rejected = 2,
    
    /// <summary>
    /// The suggestion has been successfully implemented in the workflow.
    /// Indicates completion of the improvement process with measurable outcomes.
    /// </summary>
    Implemented = 3,
    
    /// <summary>
    /// The suggestion has been postponed for future consideration.
    /// Indicates the recommendation has merit but timing or resources prevent immediate action.
    /// </summary>
    Deferred = 4,
    
    /// <summary>
    /// The suggestion is currently being evaluated by stakeholders.
    /// Indicates active review process including impact assessment and feasibility analysis.
    /// </summary>
    UnderReview = 5
}
